apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default
spec:
  rules:
  - host: 18.209.241.10
    http:
      paths:
        backend:
          service:
            name: menu-front-service
            port: 
              number: 3000
